- name: copy elastic search repo
  ansible.builtin.template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: install logstash
  ansible.builtin.dnf:
    name: logstash
    state: installed

- name: copy logstash conf
  ansible.builtin.template:
    src: logstash.conf
    dest: /etc/logstash/conf.d/logstash.conf