- name: get secrets from vault
  hosts: localhost
  tasks:
   - name: get vault common ssh credentials
     ansible.builtin.lineinfile:
       path: secrets.json
       line: "{{ lookup('hashi_vault', 'secret=expense/data/common token={{vault_token}} url=https://52.203.233.142:8200 validate_certs=False')}}"
       create: yes

   - name: get vault expense credentials
     ansible.builtin.lineinfile:
       path: app.json
       line: "{{ lookup('hashi_vault', 'secret=expense-app/data/{{component_name}} token={{vault_token}} url=https://52.203.233.142:8200 validate_certs=False')}}"
       create: yes



