- name: get secrets from vault
  hosts: localhost
  tasks:
#   - name: get vault common ssh credentials
#     ansible.builtin.lineinfile:
#       path: ~/secrets.json
#       line: "{{ lookup('hashi_vault', 'secret=common/data/vault token={{vault_token}} url=https://54.227.168.66:8200 validate_certs=False')}}"
#       create: yes
#
#   - name: get vault expense credentials
#     ansible.builtin.lineinfile:
#       path: ~/app.json
#       line: "{{ lookup('hashi_vault', 'secret=common/data/{{component_name}} token={{vault_token}} url=https://54.227.168.66:8200 validate_certs=False')}}"
#       create: yes

    - name: get vault expense credentials
      ansible.builtin.lineinfile:
        path: ~/secrets.json
        line: "{{ lookup('hashi_vault', 'secret={{ item }} token={{vault_token}} url=https://3.81.78.89:8200 validate_certs=False')}}"
        create: yes
      loop:
        - common/data/vault
        - common/data/{{component_name}}

    - name: multi json object into single json
      ansible.builtin.shell: for i in $(ls ~/*.json); do echo  $(cat $i); done | sed -e 's\}{\,\ >~/secrets.json




