- name: Install nginx package
  ansible.builtin.dnf:
    name: nginx
    state: latest

#- name: start and enabled nginx service
#  ansible.builtin.systemd_service:
#    name: nginx
#    state: started
#    enabled: yes
- name: copy expense conf
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import code commonly
  ansible.builtin.import_role:
    name: common
    tasks_from: pre-req.yml

- name: restart nginx service
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
    enabled: yes

