#- name: set name
#  ansible.builtin.shell: sudo set-prompt elk

- name: copy elastic repo
  ansible.builtin.template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install elastic search
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: start service
  ansible.builtin.systemd_service:
    name: elasticsearch
    state: started
    enabled: yes
    daemon_reload: yes

- name: Install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: select and update port
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port: 5601'
    line: "server.port: 5601"

- name: select and update host
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host: localhost'
    line: "server.host: 0.0.0.0"

- name: start kibana service
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted


