- name: make a runner directory
  ansible.builtin.file:
    path: /home/ec2-user/actions-runner
    state: directory
    owner: ec2-user
    group: ec2-user


- name: Download runner
  ansible.builtin.unarchive:
    src: https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz
    dest: /home/ec2-user/actions-runner
    remote_src: yes
  become_user: ec2-user

#- name: display secrets
#  ansible.builtin.debug:
#    msg: "{{ token }}"
#
#- name: display secrets
#  ansible.builtin.debug:
#    msg: "{{ token.actions }}"
- name: Uninstall runner service
  ansible.builtin.shell: ./svc.sh  uninstall
  args:
    chdir: /home/ec2-user/actions-runner/

- name: Install runner config
  ansible.builtin.shell: ./config.sh remove  --token {{token.actions}}; ./config.sh --unattended --replace --url https://github.com/devps23  --token {{token.actions}}
  args:
    chdir: /home/ec2-user/actions-runner
  become_user: ec2-user

- name: Start runner
  ansible.builtin.shell: ./svc.sh install ; ./svc.sh start
  args:
    chdir: /home/ec2-user/actions-runner/

- name: Install Java
  ansible.builtin.dnf:
    name: java-17-openjdk
    state: installed

- name: Download sonar scanner cli
  ansible.builtin.unarchive:
    src: https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-6.0.0.4432-linux.zip?_gl=1*vfewuu*_gcl_au*MTc2NjYxNDU5Mi4xNzE4ODgxMjY2*_ga*MTQ0OTE4NjMwLjE3MTg4ODEyNjc.*_ga_9JZ0GZ5TC6*MTcxOTIxMDcwNC40LjAuMTcxOTIxMDcwNC42MC4wLjA.
    dest: /opt
    remote_src: yes







