- name: Download  and unarchive node exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{version}}/node_exporter-{{version}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes

- name: copy node_exporter service
  ansible.builtin.template:
    src: exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Start node exporter service
  ansible.builtin.systemd_service:
    name: node_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
