vault_token: "'{{ lookup('ansible.builtin.env', 'vault_token') }}'"
secrets: "{{ lookup('hashi_vault', 'secret=expense/data/common  token={{ vault_token }} url=https://54.162.217.77:8200 validate_certs=False')}}"
jenkins_setup: false
jenkins_jobs: false