- name: set artifactory prompt
  ansible.builtin.shell: set-prompt artifactory

- name: Add artifactory  user
  ansible.builtin.user:
    name: artifact

- name: create artifactory directory
  ansible.builtin.file:
    path: /opt/artifactory
    state: directory
    owner: artifact
    group: artifact

- name: Download and unarchive artifactory
  ansible.builtin.unarchive:
    src:  https://releases.jfrog.io/artifactory/bintray-artifactory/org/artifactory/oss/jfrog-artifactory-oss/7.71.17/jfrog-artifactory-oss-7.71.17-linux.tar.gz
    dest: /opt/artifactory
    remote_src: yes
    owner: artifact
    group: artifact
  become_user: artifact

- name: setup artifactory service
  ansible.builtin.template:
    src: artifactory.service
    dest: /etc/systemd/system/artifactory.service

- name: start service
  ansible.builtin.systemd_service:
    name: artifactory
    state: started
    enabled: yes
    daemon_reload: yes




