- name: copy elastic repo file
  ansible.builtin.template:
    src: elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo

- name: Install elsatic search
  ansible.builtin.dnf:
    name: elasticsearch
    state: installed

- name: elastic service
  ansible.builtin.systemd_service:
    name: elastic
    state: restarted
    enabled: true
    daemon_reload: true

- name: Install kibana
  ansible.builtin.dnf:
    name: kibana
    state: installed

- name: elastic service
  ansible.builtin.systemd_service:
    name: kibana
    state: started
    enabled: true



- name: selact and update port
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.port: 5601'
    line: "server.port: 5601"

- name: selact and update host
  ansible.builtin.lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#server.host: localhost'
    line: "server.host: 0.0.0.0"

- name: kibana service
  ansible.builtin.systemd_service:
    name: kibana
    state: restarted





